### ISSUE TITLE
IndentationError: expected an indented block in flex_model.py (dev branch)

### ISSUE THREAD

**Issue by martinhonerk** [tim-fiola/network_traffic_modeler_py3#32]
Hello Tim,

there seems to miss something at line 503 in file flex_model.py:

Traceback (most recent call last):
  File "test_traffic_eng_features.py", line 8, in <module>
    from pyNTM import PerformanceModel
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/martin/simu_v2/lib/python3.7/site-packages/pyNTM-2.0-py3.7.egg/pyNTM/__init__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
  File "/home/martin/simu_v2/lib/python3.7/site-packages/pyNTM-2.0-py3.7.egg/pyNTM/flex_model.py", line 503
    max_split = max([split for split in traffic_splits_per_interface.values()])
    ^
IndentationError: expected an indented block

Kind Regards...
Martin

**Comment by tim-fiola** [comment]
Hi Martin.  Thanks for bringing this to my attention.  I'll check on that.  The dev branch is currently broken as it is until I finish the igp shortcuts feature (as I build I'm having to wreck/rebuild some stuff).  However, I will take a look at this and make sure I get that fixed.  I'm hoping to have that done this weekend sometime.

Thank you!
Tim

**Comment by tim-fiola** [comment]
fixed
